Wallet/Controllers/AccountApiController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WalletServices.BudgetManagementService;
using WalletServices.Entities;

namespace Wallet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountApiController : ControllerBase
    {
        private readonly IWalletService _dataService;

        public AccountApiController(IWalletService dataService)
        {
            _dataService = dataService;
        }

        /// <summary>
        /// Create the new account
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     POST /AccountApi/Create
        ///     {
        ///        "name": "Item1",
        ///        "sum": 100
        ///     }
        ///
        /// </remarks>
        /// <param name="name">The name of account</param>
        /// <param name="sum">The account balance</param>
        /// <returns>The created Account</returns>
        [HttpPost]
        public async Task<IActionResult> Create([FromForm]string name, [FromForm]int sum)
        {
            var account = new Account()
            {
                Sum = sum,
                Name = name
            };

            if (ModelState.IsValid)
            {
                _dataService.AddAccount(account);
            }

            return RedirectToAction("Index", "Accounts");
        }


        /// <summary>
        /// Delete the account
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     POST /AccountApi/Delete
        ///     {
        ///        "id": 1
        ///     }
        ///
        /// </remarks>
        /// <returns>The removed Account</returns>
        [HttpPost("api/AccountApi/Delete")]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            _dataService.RemoveAccount(id);
            return RedirectToAction("Index", "Accounts");
        }
    }
}

Wallet/Controllers/AccountTransferApiController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WalletServices.BudgetManagementService;
using WalletServices.Entities;

namespace Wallet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountTransferApiController : ControllerBase
    {
        private readonly IWalletService _dataService;

        public AccountTransferApiController(IWalletService dataService)
        {
            _dataService = dataService;
        }

        /// <summary>
        /// Transfer money between the Accounts
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     POST /AccountsTransfer/Create
        ///     {
        ///        "sum":1,
        ///        "comment": "Comment",
        ///        "senderId": 1,
        ///        "recieverId": 2
        ///     }
        ///
        /// </remarks>
        /// <returns>The transfer between Accounts</returns>
        [HttpPost]
        public async Task<IActionResult> Create(
            [FromForm]int senderId, [FromForm]int recieverId, [FromForm]string comment, 
            [FromForm]int sum)
        {
            if (ModelState.IsValid)
            {
                _dataService.TransferSumToAnotherAccount(
                    sumToSend:sum,
                    comment: comment,
                    senderAccountId: senderId,
                    recieverAccountId: recieverId);
            }

            return RedirectToAction("Index", "Accounts");
        }

        /// <summary>
        /// Transfer money between the Accounts
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     GET /AccountsTransfer
        ///     {
        ///     
        ///     }
        ///
        /// </remarks>
        /// <returns>The transfer between Accounts</returns>
        [HttpGet]
        public async Task<IEnumerable<AccountsTransfer>> Get()
        {
            return _dataService.GetAccountsTransfers();
        }
    }
}

Wallet/Controllers/AccountsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WalletServices.BudgetManagementService;
using WalletServices.Entities;

namespace Wallet.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IWalletService _context;

        public AccountsController(IWalletService context)
        {
            _context = context;
        }

        // GET: Accounts
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            IEnumerable<Account> accounts;

            accounts = _context.GetAccounts();

            if (!string.IsNullOrEmpty(searchString))
            {
                accounts = accounts.Where(a => a.Name.Contains(searchString));
            }

            ViewBag.Incomes = _context
                .GetIncomeStatistics()
                .Select(p => new { y = p.Value, indexLabel = p.Key });
            ViewBag.Expenses = _context.GetExpenseStatistics()
                .Select(p => new { y = p.Value, indexLabel = p.Key });

            return View(accounts);
        }

        public ActionResult Doughnut()
        {
            return View();
        }


    }
}

Wallet/Controllers/ExpenseApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WalletServices.BudgetManagementService;
using WalletServices.Entities;

namespace Wallet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ExpenseApiController : ControllerBase
    {
        private readonly IWalletService _dataService;

        public ExpenseApiController(IWalletService dataService)
        {
            _dataService = dataService;
        }

        /// <summary>
        /// Add new Expense
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     POST /Expense/Create
        ///     {
        ///        "expenseType" = [Food],
        ///        "comment" = "comment",
        ///        "accountId" = 1,
        ///        "sum" = 1
        ///     }
        ///
        /// </remarks>
        /// <returns>The new Expense</returns>
        [HttpPost]
        public async Task<IActionResult> Create(
            [FromForm]int accountId, [FromForm]string expenseType, [FromForm]string comment, [FromForm]int sum)
        {
            var expense = new Expense()
            {
                ExpenseType = Enum.Parse<ExpenseTypeName>(expenseType),
                Comment = comment,
                CreatedAt = DateTime.Now,
                Sum = sum
            };

            if (ModelState.IsValid)
            {
                _dataService.AddExpense(accountId, expense);
            }

            return RedirectToAction("Index", "Accounts");
        }
    }
}

Wallet/Controllers/IncomeApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WalletServices.BudgetManagementService;
using WalletServices.Entities;

namespace Wallet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class IncomeApiController : ControllerBase
    {
        private readonly IWalletService _dataService;

        public IncomeApiController(IWalletService dataService)
        {
            _dataService = dataService;
        }

        /// <summary>
        /// Add new Income
        /// </summary>
        /// <remarks>
        /// Sample request:
        ///
        ///     POST /Income/Create
        ///     {
        ///        "incomeType" = [Salary],
        ///        "comment" = "comment",
        ///        "accountId" = 1,
        ///        "sum" = 1
        ///     }
        ///
        /// </remarks>
        /// <returns>The new Income</returns>
        [HttpPost]
        public async Task<IActionResult> Create(
            [FromForm]int accountId, [FromForm]string incomeType, [FromForm]string comment, [FromForm]int sum)
        {
            var income = new Income()
            {
                IncomeType = Enum.Parse<IncomeTypeName>(incomeType),
                Comment = comment,
                CreatedAt = DateTime.Now,
                Sum = sum
            };

            if (ModelState.IsValid)
            {
                _dataService.AddIncome(accountId, income);
            }

            return RedirectToAction("Index", "Accounts");
        }
    }
}

Wallet/Views/Accounts/Index.cshtml
@using WalletServices.Entities
@model IEnumerable<WalletServices.Entities.Account>

@{
	ViewData["Title"] = "Index";
}

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		function showHideElms(elmName) {
			$(elmName).toggle();
		}

	</script>
</head>

<body>
    @if (Model.Any(m => m.Expenses.Any()) && Model.Any(m => m.Incomes.Any()))
    {
        <script type="text/javascript">
			window.onload = function () {
					var chart = new CanvasJS.Chart("chartContainer", {
					title: {
						text: "Accounts statistics | Incomes"
					},
					animationEnabled: true,
					legend: {
						fontSize: 20,
						fontFamily: "Helvetica"
					},
					theme: "light2",
					data: [
						{
							type: "doughnut",
							indexLabelFontFamily: "Garamond",
							indexLabelFontSize: 20,
							indexLabel: "{label} {y}%",
							startAngle: -20,
							toolTipContent: "{label} {y}%",
							dataPoints: @Html.Raw(Json.Serialize(ViewBag.Incomes)),
						}
					]
				});

				chart.render();

				var chartExp = new CanvasJS.Chart("chartContainerExp", {
					title: {
						text: "Accounts statistics | Expenses"
					},
					animationEnabled: true,
					legend: {
						fontSize: 20,
						fontFamily: "Helvetica"
					},
					theme: "light2",
					data: [
						{
							type: "doughnut",
							indexLabelFontFamily: "Garamond",
							indexLabelFontSize: 20,
							indexLabel: "{label} {y}%",
							startAngle: -20,
							toolTipContent: "{label} {y}%",
							dataPoints: @Html.Raw(Json.Serialize(ViewBag.Expenses)),
						}
					]
				});

				chartExp.render();
			};
        </script>

        <div id="chartContainer" style="height: 370px; width: 100%;"></div>
        <div id="chartContainerExp" style="height: 370px;"></div>
    }

    <p style="text-align: center; color: white;">
        <a class="btn btn-success" onclick="showHideElms('.income_add')">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add income
        </a>
        <a class="btn btn-success" onclick="showHideElms('.expense_add')">
            <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Add expense
        </a>
        <a class="btn btn-success" onclick="showHideElms('.account_transfer')">
            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> Add account transfer
        </a>
    </p>


    <form asp-action="Index" method="get">
        <div class="form-actions no-color mb-5">
            <p>
                <br>
                <span style="font-size:2rem">Choose account:</span>
                
                <input class="form-control mr-sm-2 mb-3" type="search" placeholder="Search" aria-label="Search" name="SearchString" value="@ViewData["currentFilter"]">
                <button class="btn btn-warning mt-2 my-2 my-sm-0 mr-3" type="submit" value="Search">Search</button>
                <a asp-action="Index">Back to Full List</a>
            </p>
        </div>
    </form>
    

    <div class="income_add" style="display:none">
        @using (Html.BeginForm("Create", "IncomeApi", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-4">
                    <form>
                        <div class="form-group">
                            <label>Income type</label>
                            <select class="custom-select" id="incomeType" name="incomeType">
                                @foreach (var incomeType in Enum.GetNames(typeof(IncomeTypeName)))
                                {
                                    <option value="@incomeType">@incomeType</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Account</label>
                            <select class="custom-select" id="accountId" name="accountId">
                                @foreach (var account in Model)
                                {
                                    <option value="@account.Id">@account.Name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Sum</label>
                            <input type="number" name="sum" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <input type="text" name="comment" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>

    <div class="expense_add" style="display:none">
        @using (Html.BeginForm("Create", "ExpenseApi", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-4">
                    <form>
                        <div class="form-group">
                            <label>Income type</label>
                            <select class="custom-select" name="expenseType">
                                @foreach (var incomeType in Enum.GetNames(typeof(ExpenseTypeName)))
                                {
                                    <option value="@incomeType">@incomeType</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Account</label>
                            <select class="custom-select" name="accountId">
                                @foreach (var account in Model)
                                {
                                    <option value="@account.Id">@account.Name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Sum</label>
                            <input type="number" name="sum" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <input type="text" name="comment" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>

    <div class="account_transfer" style="display:none">
        @using (Html.BeginForm("Create", "AccountTransferApi", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-4">
                    <form>
                        <div class="form-group">
                            <label>Income type</label>
                            <select class="custom-select" name="senderId">
                                @foreach (var account in Model)
                                {
                                    <option value="@account.Id">@account.Name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Account</label>
                            <select class="custom-select" name="recieverId">
                                @foreach (var account in Model)
                                {
                                    <option value="@account.Id">@account.Name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Sum</label>
                            <input type="number" name="sum" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <input type="text" name="comment" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sum)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sum)
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "AccountApi", FormMethod.Post))
                        {
                            <form>
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" class="btn btn-danger" value="Delete" />
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-success" onclick="showHideElms('.account_add')" style="color: white;">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add account
    </a>

    <div class="account_add" style="display:none">
        @using (Html.BeginForm("Create", "AccountApi", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-4">
                    <form>
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Sum</label>
                            <input type="number" name="sum" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>

    @foreach (var item in Model)
    {
        <h3>@item.Name</h3>
        <table class="table table-striped">
            <thead style="background-color:#343a40">
                <tr style="color:white">
                    <td>
                        Type
                    </td>
                    <td>
                        Comment
                    </td>
                    <td>
                        Created At
                    </td>
                    <td>
                        Sum
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="4" style="background-color:lightgrey">Incomes</td>
                </tr>
                @foreach (var income in item.Incomes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => income.IncomeType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => income.Comment)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => income.CreatedAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => income.Sum)
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4" style="background-color:lightgrey">Expenses</td>
                </tr>
                @foreach (var expense in item.Expenses)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => expense.ExpenseType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => expense.Comment)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => expense.CreatedAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => expense.Sum)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    <div style="padding-bottom: 50px"></div>
</body>